version: "3.8"

services:
  app1:
    build:
      context: ./app-1
    expose:
      - "3000"
    restart: unless-stopped
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
    restart: unless-stopped
