version: "3.8"

services:
  app1:
    build:
      context: ./app-1
    expose:
      - "3000"
    restart: unless-stopped

  app2:
    build:
      context: ./app-2
    expose:
      - "3000"
    restart: unless-stopped

  website:
    build:
      context: ./website
    expose:
      - "80"
    restart: unless-stopped

  cert-manager:
    build:
      context: ./cert-manager
    volumes:
      - ./log:/var/log
      - ./letsencrypt:/letsencrypt
      - ./cert:/etc/letsencrypt
    expose:
      - "80"
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/letsencrypt
      - ./cert:/cert
    depends_on:
      - app1
      - app2
      - website
    restart: unless-stopped
